update(docker): add redis image to docker-compose

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -6,9 +6,8 @@ commit_regex='^((feat|fix|doc|add|update|delete) ?(\([A-z]+\))?: .+)(\.)?|Merge.
 # if the commit message is different from the regex
 if ! grep -iqE "$commit_regex" "$1"; then
     # echo error
-    echo -e "
-\e[31mError: your message does not respect the commit pattern: 
-$commit_regex\e[39m" >&2
+    echo -e "\Error: your message does not respect the commit pattern: 
+    $commit_regex" >&2
     # then exit
     exit 1
 fi
